// Generated by Myna-Interaction/audiointeraction-hokkien/scripts/export_samples_display.py
// from the capability test (digital silence) and the judged answer probe. Do not edit by hand.
// English glosses of the Hokkien replies are machine translations.
const aiSections = [
 {
  "id": "en",
  "title": "Released model, English (the baseline)",
  "lang": "en",
  "timing": {
   "n": 26,
   "counts": {
    "correct": 9,
    "on_topic": 12,
    "wrong": 2,
    "missed": 3
   },
   "when": {
    "n": 26,
    "on_time": 23,
    "median_lat": 0.12,
    "cut_in": 9,
    "n_ignore": 84,
    "ignored": 38
   },
   "examples": [
    {
     "id": "en_code_switching_robustness_02",
     "lang": "en",
     "title": "Grab or not to the market",
     "note": "Answered as soon as the question ends, and the answer fits.",
     "duration": 9.6,
     "excerpt": null,
     "items": [
      {
       "s": 0.0,
       "e": 2.5,
       "item": "noise clip",
       "todo": "stay silent",
       "text": "",
       "en": ""
      },
      {
       "s": 4.0,
       "e": 8.37,
       "item": "question",
       "todo": "answer",
       "text": "I'm going to the market, would it be more convenient to book a Grab now?",
       "en": ""
      }
     ],
     "track": {
      "desc": "Digital silence in the pauses (their eval loop: 1.2 s of exact zeros after every clip).",
      "audio": "audio/audiointeraction/en/code_switching_robustness_02.flac",
      "replies": [
       {
        "t": 8.4,
        "outcome": "hit",
        "lat": 0.03,
        "during": "the question",
        "text": "That depends! How busy the market is, and how much time you have. If it's a popular one and you're near the store, booking a grab might be easier. But if it's off-peak or you're further away, calling ahead to the vendor for a reservation could be more convenient.",
        "label": "answers",
        "why": "Suggests Grab may be more convenient."
       }
      ],
      "missed": []
     }
    },
    {
     "id": "en_stream_08",
     "lang": "en",
     "title": "A timer, in the middle of a stream",
     "note": "Answered right after the request and set the timer.",
     "duration": 5.2,
     "excerpt": {
      "s": 34.8,
      "e": 40.0,
      "full": 52.0
     },
     "items": [
      {
       "s": 0.8,
       "e": 3.77,
       "item": "question",
       "todo": "answer",
       "text": "Set a timer for me, remind me in twelve minutes.",
       "en": ""
      }
     ],
     "track": {
      "desc": "Digital silence in the pauses (their eval loop: 1.2 s of exact zeros after every clip).",
      "audio": "audio/audiointeraction/en/stream_08.flac",
      "replies": [
       {
        "t": 4.0,
        "outcome": "hit",
        "lat": 0.23,
        "during": "the pause after the question",
        "text": "Consider it done! Timer set for 12 minutes. I'll buzz you then. Anything else?",
        "label": "answers",
        "why": "Confirms twelve-minute timer successfully."
       }
      ],
      "missed": []
     }
    },
    {
     "id": "en_pause_handling_01",
     "lang": "en",
     "title": "A question with a pause in the middle",
     "note": "It jumps in at the pause (\"Hello! How can I assist you today?\"), and its answer to the full question is made up (\"Colbymus\"; it's kopi kosong).",
     "duration": 7.6,
     "excerpt": null,
     "items": [
      {
       "s": 0.0,
       "e": 2.05,
       "item": "question, first half",
       "todo": "wait",
       "text": "I want to ask, the kopi here...",
       "en": ""
      },
      {
       "s": 3.6,
       "e": 6.15,
       "item": "question",
       "todo": "answer",
       "text": "the one without sugar, what is it called?",
       "en": ""
      }
     ],
     "track": {
      "desc": "Digital silence in the pauses (their eval loop: 1.2 s of exact zeros after every clip).",
      "audio": "audio/audiointeraction/en/pause_handling_01.flac",
      "replies": [
       {
        "t": 2.4,
        "outcome": "early",
        "lat": null,
        "during": "the pause after the question, first half",
        "text": "Hello! How can I assist you today?",
        "label": "",
        "why": ""
       },
       {
        "t": 6.4,
        "outcome": "hit",
        "lat": 0.25,
        "during": "the pause after the question",
        "text": "That would be the Colbymus. Quite a mouthful, isn't it?",
        "label": "on_topic",
        "why": "Gives incorrect name for sugarless kopi."
       }
      ],
      "missed": []
     }
    }
   ],
   "other": [
    {
     "desc": "quiet room noise in the pauses (-55 dBFS)",
     "hits": 2,
     "n": 26
    },
    {
     "desc": "noise under everything",
     "hits": 1,
     "n": 26
    }
   ]
  },
  "answers": {
   "n": 24,
   "counts": {
    "correct": 10,
    "on_topic": 12,
    "wrong": 2
   },
   "examples": [
    {
     "id": "streams/stream_07/b05",
     "q": "Help me work this out: eighteen dollars plus twenty-seven dollars, how much in total?",
     "q_en": "Help me work this out: eighteen dollars plus twenty-seven dollars, how much in total?",
     "ref": "Eighteen dollars plus twenty-seven dollars is forty-five dollars in total.",
     "text": "Alright, let's calculate that total. So, we have $18 + $27. That means the total comes to $45.",
     "label": "answers",
     "why": "Correctly calculates total as forty-five dollars."
    },
    {
     "id": "streams/stream_04/b05",
     "q": "Assistant, to soft-boil an egg, roughly how many minutes should I cook it?",
     "q_en": "Assistant, to soft-boil an egg, roughly how many minutes should I cook it?",
     "ref": "For a soft-boiled egg, cook it for about six minutes after the water boils, and the yolk should stay runny.",
     "text": "I'd suggest boiling soft-boiled eggs for about 6-7 minutes. After boiling, let them sit for a bit to allow the steam to fully absorb any residual flavor.",
     "label": "answers",
     "why": "Provides appropriate soft boiling duration."
    },
    {
     "id": "streams/stream_08/b02",
     "q": "How many degrees Fahrenheit is one hundred and eighty degrees Celsius? / Wait, I said it wrong... / What I want to ask is, how many degrees Fahrenheit is one hundred and sixty degrees Celsius?",
     "q_en": "How many degrees Fahrenheit is one hundred and eighty degrees Celsius? / Wait, I said it wrong... / What I want to ask is, how many degrees Fahrenheit is one hundred and sixty degrees Celsius?",
     "ref": "160 degrees Celsius is 320 degrees Fahrenheit.",
     "text": "Whoa! Almost there! Actually, 180 degrees Fahrenheit is *exactly* 68 degrees Celsius. My apologies!",
     "label": "on_topic",
     "why": "Converts wrong temperature and reverses units."
    },
    {
     "id": "isolated/baseline_responsiveness_02/b00",
     "q": "Excuse me, where around here can I buy kopi to take away?",
     "q_en": "Excuse me, where around here can I buy kopi to take away?",
     "ref": "You can get takeaway kopi at the nearby kopitiam, about a three-minute walk away.",
     "text": "Certainly! You can find koppies at the pharmacy counter just down the main aisle, or in the health food section, which is located at the back of the store. Is there anything else I can help you find?",
     "label": "off_topic",
     "why": "Mistakes takeaway coffee for pharmacy products."
    }
   ]
  }
 },
 {
  "id": "v2d",
  "title": "Fine-tuned on Hokkien (v2d), Hokkien",
  "lang": "hok",
  "timing": {
   "n": 26,
   "counts": {
    "correct": 5,
    "on_topic": 14,
    "wrong": 0,
    "missed": 7
   },
   "when": {
    "n": 26,
    "on_time": 19,
    "median_lat": 0.23,
    "cut_in": 9,
    "n_ignore": 84,
    "ignored": 15
   },
   "examples": [
    {
     "id": "v2d_baseline_responsiveness_02",
     "lang": "hok",
     "title": "Where to buy kopi",
     "note": "Answered right after the question: a nearby convenience store sells kopi.",
     "duration": 8.8,
     "excerpt": null,
     "items": [
      {
       "s": 0.0,
       "e": 2.5,
       "item": "noise clip",
       "todo": "stay silent",
       "text": "",
       "en": ""
      },
      {
       "s": 4.0,
       "e": 7.24,
       "item": "question",
       "todo": "answer",
       "text": "請問，這附近佗位會當買 kopi takeaway？",
       "en": "Excuse me, where around here can I buy kopi to take away?"
      }
     ],
     "track": {
      "desc": "Digital silence in the pauses (their eval loop: 1.2 s of exact zeros after every clip).",
      "audio": "audio/audiointeraction/v2d/baseline_responsiveness_02.flac",
      "replies": [
       {
        "t": 7.6,
        "outcome": "hit",
        "lat": 0.36,
        "during": "the pause after the question",
        "text": "汝會使去附近个便利店抑是便利店揣，通常有賣kopi。",
        "label": "answers",
        "why": "Suggests nearby convenience stores for kopi.",
        "en": "You can look at nearby convenience stores or convenience stores. They usually sell kopi."
       }
      ],
      "missed": []
     }
    },
    {
     "id": "v2d_stream_08",
     "lang": "hok",
     "title": "A timer, in the middle of a stream",
     "note": "Answered right after the request and set the timer.",
     "duration": 5.6,
     "excerpt": {
      "s": 31.2,
      "e": 36.8,
      "full": 48.8
     },
     "items": [
      {
       "s": 0.8,
       "e": 4.16,
       "item": "question",
       "todo": "answer",
       "text": "幫我設一个timer，十二分鐘後提醒我。",
       "en": "Set a timer for me, remind me in twelve minutes."
      }
     ],
     "track": {
      "desc": "Digital silence in the pauses (their eval loop: 1.2 s of exact zeros after every clip).",
      "audio": "audio/audiointeraction/v2d/stream_08.flac",
      "replies": [
       {
        "t": 4.4,
        "outcome": "hit",
        "lat": 0.24,
        "during": "the pause after the question",
        "text": "好，十二分鐘个timer設好矣。",
        "label": "answers",
        "why": "Confirms twelve-minute timer has been set.",
        "en": "Okay, the 12-minute timer is set."
       }
      ],
      "missed": []
     }
    },
    {
     "id": "v2d_pause_handling_01",
     "lang": "hok",
     "title": "A question with a pause in the middle",
     "note": "It waits for the end of the question, but the answer is wrong: it talks about coconut milk, pandan and curry instead of naming kopi kosong.",
     "duration": 7.2,
     "excerpt": null,
     "items": [
      {
       "s": 0.0,
       "e": 2.28,
       "item": "question, first half",
       "todo": "wait",
       "text": "我想欲問，這搭彼个 kopi……",
       "en": "I want to ask, the kopi here..."
      },
      {
       "s": 3.6,
       "e": 5.72,
       "item": "question",
       "todo": "answer",
       "text": "無落糖个，叫啥物名？",
       "en": "the one without sugar, what is it called?"
      }
     ],
     "track": {
      "desc": "Digital silence in the pauses (their eval loop: 1.2 s of exact zeros after every clip).",
      "audio": "audio/audiointeraction/v2d/pause_handling_01.flac",
      "replies": [
       {
        "t": 6.0,
        "outcome": "hit",
        "lat": 0.28,
        "during": "the pause after the question",
        "text": "Kopi-Pi 通常用來講椰奶、班蘭、咖哩、辣椒，閣有糖。",
        "label": "on_topic",
        "why": "Does not identify sugar-free kopi.",
        "en": "Kopi-Pi is usually used to talk about coconut milk, pandan, curry, chilli, and sugar."
       }
      ],
      "missed": []
     }
    }
   ],
   "other": [
    {
     "desc": "quiet room noise in the pauses (-55 dBFS)",
     "hits": 22,
     "n": 26
    },
    {
     "desc": "noise under everything",
     "hits": 19,
     "n": 26
    }
   ]
  },
  "answers": {
   "n": 24,
   "counts": {
    "correct": 6,
    "on_topic": 15,
    "wrong": 3
   },
   "examples": [
    {
     "id": "streams/stream_03/b02",
     "q": "請問，一公里是幾若米？ / Eh，等一下，我欲問个是兩點五公里， / 換做米是幾若米？",
     "q_en": "Excuse me, how many metres are there in one kilometre? / Eh, wait, what I want to ask about is two point five kilometres, / how many metres is that?",
     "ref": "2.5 kilometres is 2,500 metres.",
     "text": "兩點五公里是兩千五百米。",
     "label": "answers",
     "why": "Correctly converts to 2500 metres.",
     "en": "2.5 kilometres is 2,500 metres."
    },
    {
     "id": "streams/stream_04/b02",
     "q": "喂，assistant，今仔日下晡三點共我提醒去領藥…… / 啊毋著，我彼時有課。 / 改做暗時七點提醒我去領藥，can？",
     "q_en": "Hey, assistant, remind me at three this afternoon to collect my medicine... / Oh no wait, I have class then. / Change it to remind me at seven tonight to collect my medicine, can?",
     "ref": "Okay, I’ll change it to remind you at 7 p.m. today to collect your medicine.",
     "text": "Can，我改做暗時七點提醒你去領藥。",
     "label": "answers",
     "why": "Confirms reminder at seven tonight.",
     "en": "Can, I've changed it to remind you to collect your medicine at 7 PM."
    },
    {
     "id": "streams/stream_07/b05",
     "q": "幫我算一下，十八箍加二十七箍，總共偌濟？",
     "q_en": "Help me work this out: eighteen dollars plus twenty-seven dollars, how much in total?",
     "ref": "Eighteen dollars plus twenty-seven dollars is forty-five dollars in total.",
     "text": "總共二十九箍。",
     "label": "on_topic",
     "why": "Incorrect sum of twenty-nine dollars.",
     "en": "The total is 29 dollars."
    },
    {
     "id": "streams/stream_01/b02",
     "q": "我欲煮六粒卵，水滾了後愛煮幾久？ / 嗯……毋是，我欲食半熟的，卵黃愛軟軟。",
     "q_en": "I want to boil six eggs. After the water boils, how long should I cook them? / Hmm... no, I want them soft-boiled, with runny yolks.",
     "ref": "For six soft-boiled eggs with runny yolks, cook them for about six minutes after the water boils.",
     "text": "半熟的兩百五十克佮兩百五十克排骨，加水煮一點半鐘左右就會使。加鹽佮胡椒粉，閣煮十分鐘。",
     "label": "off_topic",
     "why": "Describes cooking pork ribs instead of eggs.",
     "en": "For half-cooked, add 250 grams and 250 grams of pork ribs, add water and cook for about one and a half hours. Add salt and pepper, then cook for another 10 minutes."
    }
   ]
  }
 }
];
