// Generated by Myna-Interaction/audiointeraction-hokkien/scripts/export_samples_display.py
// from the capability test of the released AudioInteraction-3B (2026-10-01). Do not edit by hand.
const aiSamples = [
 {
  "id": "en_baseline_responsiveness_01",
  "lang": "en",
  "title": "One question",
  "note": "With digital silence after the question it answers straight away. Put any real noise in that pause, even noise too quiet to hear, and it says nothing.",
  "tracks": [
   {
    "cond": "zeros_perfile",
    "label": "Digital silence in the pause",
    "desc": "Their eval loop: after every clip, 1.2 s of exact zeros.",
    "audio": "audio/audiointeraction/en_baseline_responsiveness_01/zeros_perfile.flac",
    "replies": [
     {
      "t": 8.0,
      "outcome": "hit",
      "lat": 0.19,
      "p": 1.0,
      "during": "the question",
      "text": "Ah, you're looking for the deliciousness! Well, you've found me. Hainanese chicken rice is a local favorite. Head straight down this aisle, and you'll see a small restaurant with a sign that says \"Authentic Chinese Cuisine.\" That's the one!"
     }
    ],
    "missed": [],
    "hits": 1,
    "targets": 1
   },
   {
    "cond": "real-70_live",
    "label": "Faint room noise in the pause (-70 dBFS)",
    "desc": "Real room ambience (MUSAN) at -70 dBFS fills the pause. You will not hear it unless you turn the volume right up.",
    "audio": "audio/audiointeraction/en_baseline_responsiveness_01/real-70_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 7.81,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 1
   },
   {
    "cond": "real-40_live",
    "label": "Normal room noise in the pause (-40 dBFS)",
    "desc": "Real room ambience at -40 dBFS, an ordinary room.",
    "audio": "audio/audiointeraction/en_baseline_responsiveness_01/real-40_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 7.81,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 1
   },
   {
    "cond": "bed20_live",
    "label": "Noise under everything, 20 dB below speech",
    "desc": "The paper's training recipe: a continuous noise track under the speech and the pauses.",
    "audio": "audio/audiointeraction/en_baseline_responsiveness_01/bed20_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 7.81,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 1
   },
   {
    "cond": "demo_quiet",
    "label": "Their web demo, quiet room",
    "desc": "Their demo's mic gate: nothing is sent before speech, and 0.8 s after speech stops it sends zeros. It also resets after every reply.",
    "audio": "audio/audiointeraction/en_baseline_responsiveness_01/demo_quiet.flac",
    "replies": [
     {
      "t": 8.0,
      "outcome": "hit",
      "lat": 0.19,
      "p": 1.0,
      "during": "the question",
      "text": "Ah, you're looking for the culinary treasures of Hainanese chicken rice! Well, you've found me. It's a local favorite. Several places offer it, but the big chains are usually the most reliable."
     }
    ],
    "missed": [],
    "sent": "audio/audiointeraction/en_baseline_responsiveness_01/demo_quiet.sent.flac",
    "hits": 1,
    "targets": 1
   },
   {
    "cond": "demo_bed20",
    "label": "Their web demo, noise 20 dB below speech",
    "desc": "The same demo, with room noise loud enough to keep the gate open, so the model hears the noise.",
    "audio": "audio/audiointeraction/en_baseline_responsiveness_01/demo_bed20.flac",
    "replies": [
     {
      "t": 4.0,
      "outcome": "false",
      "lat": null,
      "p": 0.5312,
      "during": "the pause after the noise clip",
      "text": "An unusual hissing sound was detected; please check for any leaks or malfunctions."
     }
    ],
    "missed": [
     {
      "t": 7.81,
      "pmax": 0.03
     }
    ],
    "sent": "audio/audiointeraction/en_baseline_responsiveness_01/demo_bed20.sent.flac",
    "hits": 0,
    "targets": 1
   }
  ],
  "duration": 9.2,
  "items": [
   {
    "s": 0.0,
    "e": 2.5,
    "item": "noise clip",
    "todo": "stay silent",
    "text": "",
    "en": ""
   },
   {
    "s": 4.0,
    "e": 7.81,
    "item": "question",
    "todo": "answer",
    "text": "Excuse me, where around here sells good Hainanese chicken rice?",
    "en": ""
   }
  ]
 },
 {
  "id": "en_multi_turn_boundary_02",
  "lang": "en",
  "title": "Two questions, a noise clip between them",
  "note": "Both questions are answered when the pauses are silent. It also talks over the noise clip.",
  "tracks": [
   {
    "cond": "zeros_perfile",
    "label": "Digital silence in the pause",
    "desc": "Their eval loop: after every clip, 1.2 s of exact zeros.",
    "audio": "audio/audiointeraction/en_multi_turn_boundary_02/zeros_perfile.flac",
    "replies": [
     {
      "t": 2.0,
      "outcome": "hit",
      "lat": 0.28,
      "p": 1.0,
      "during": "the pause after the question",
      "text": "I'm sorry, but as an AI language model, I don't have access to real-time information about parking availability. However, you can try searching for local parking garages or asking the building management for assistance."
     },
     {
      "t": 6.0,
      "outcome": "false",
      "lat": null,
      "p": 0.9999,
      "during": "the pause after the noise clip",
      "text": "Oh, really? I'm still learning! Is there anything else I can help you with?"
     },
     {
      "t": 9.2,
      "outcome": "hit",
      "lat": 0.12,
      "p": 1.0,
      "during": "the question",
      "text": "Let me check! According to my system, tomorrow at 10 AM you have a meeting with the marketing team."
     }
    ],
    "missed": [],
    "hits": 2,
    "targets": 2
   },
   {
    "cond": "real-70_live",
    "label": "Faint room noise in the pause (-70 dBFS)",
    "desc": "Real room ambience (MUSAN) at -70 dBFS fills the pause. You will not hear it unless you turn the volume right up.",
    "audio": "audio/audiointeraction/en_multi_turn_boundary_02/real-70_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 1.72,
      "pmax": 0.09
     },
     {
      "t": 9.08,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 2
   },
   {
    "cond": "real-40_live",
    "label": "Normal room noise in the pause (-40 dBFS)",
    "desc": "Real room ambience at -40 dBFS, an ordinary room.",
    "audio": "audio/audiointeraction/en_multi_turn_boundary_02/real-40_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 1.72,
      "pmax": 0.09
     },
     {
      "t": 9.08,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 2
   },
   {
    "cond": "bed20_live",
    "label": "Noise under everything, 20 dB below speech",
    "desc": "The paper's training recipe: a continuous noise track under the speech and the pauses.",
    "audio": "audio/audiointeraction/en_multi_turn_boundary_02/bed20_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 1.72,
      "pmax": 0.0
     },
     {
      "t": 9.08,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 2
   },
   {
    "cond": "demo_quiet",
    "label": "Their web demo, quiet room",
    "desc": "Their demo's mic gate: nothing is sent before speech, and 0.8 s after speech stops it sends zeros. It also resets after every reply.",
    "audio": "audio/audiointeraction/en_multi_turn_boundary_02/demo_quiet.flac",
    "replies": [
     {
      "t": 2.0,
      "outcome": "hit",
      "lat": 0.28,
      "p": 1.0,
      "during": "the pause after the question",
      "text": "I'm sorry, but as an AI language model, I don't have access to real-time information about parking availability. However, you can try searching for local parking websites or apps that provide real-time information about parking spots in your area. Good luck!"
     },
     {
      "t": 9.2,
      "outcome": "hit",
      "lat": 0.12,
      "p": 0.9924,
      "during": "the question",
      "text": "The date tomorrow is October 24, 2023."
     }
    ],
    "missed": [],
    "sent": "audio/audiointeraction/en_multi_turn_boundary_02/demo_quiet.sent.flac",
    "hits": 2,
    "targets": 2
   },
   {
    "cond": "demo_bed20",
    "label": "Their web demo, noise 20 dB below speech",
    "desc": "The same demo, with room noise loud enough to keep the gate open, so the model hears the noise.",
    "audio": "audio/audiointeraction/en_multi_turn_boundary_02/demo_bed20.flac",
    "replies": [
     {
      "t": 2.8,
      "outcome": "hit",
      "lat": 1.08,
      "p": 0.8176,
      "during": "the pause after the question",
      "text": "I'm sorry, but as an AI language model, I don't have access to your location. However, you can check the parking meter for availability at the gate of the building."
     }
    ],
    "missed": [
     {
      "t": 9.08,
      "pmax": 0.0
     }
    ],
    "sent": "audio/audiointeraction/en_multi_turn_boundary_02/demo_bed20.sent.flac",
    "hits": 1,
    "targets": 2
   }
  ],
  "duration": 10.4,
  "items": [
   {
    "s": 0.0,
    "e": 1.72,
    "item": "question",
    "todo": "answer",
    "text": "Can I park here?",
    "en": ""
   },
   {
    "s": 3.2,
    "e": 5.7,
    "item": "noise clip",
    "todo": "stay silent",
    "text": "",
    "en": ""
   },
   {
    "s": 7.2,
    "e": 9.08,
    "item": "question",
    "todo": "answer",
    "text": "What day is tomorrow?",
    "en": ""
   }
  ]
 },
 {
  "id": "en_pause_handling_01",
  "lang": "en",
  "title": "A question with a pause in the middle",
  "note": "It jumps in at the pause (\"Hello! How can I assist you?\"), then answers the full question.",
  "tracks": [
   {
    "cond": "zeros_perfile",
    "label": "Digital silence in the pause",
    "desc": "Their eval loop: after every clip, 1.2 s of exact zeros.",
    "audio": "audio/audiointeraction/en_pause_handling_01/zeros_perfile.flac",
    "replies": [
     {
      "t": 2.4,
      "outcome": "early",
      "lat": null,
      "p": 0.989,
      "during": "the pause after the question, first half",
      "text": "Hello! How can I assist you today?"
     },
     {
      "t": 6.4,
      "outcome": "hit",
      "lat": 0.25,
      "p": 1.0,
      "during": "the pause after the question",
      "text": "That would be the Colbymus. Quite a mouthful, isn't it?"
     }
    ],
    "missed": [],
    "hits": 1,
    "targets": 1
   },
   {
    "cond": "real-70_live",
    "label": "Faint room noise in the pause (-70 dBFS)",
    "desc": "Real room ambience (MUSAN) at -70 dBFS fills the pause. You will not hear it unless you turn the volume right up.",
    "audio": "audio/audiointeraction/en_pause_handling_01/real-70_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 6.15,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 1
   },
   {
    "cond": "real-40_live",
    "label": "Normal room noise in the pause (-40 dBFS)",
    "desc": "Real room ambience at -40 dBFS, an ordinary room.",
    "audio": "audio/audiointeraction/en_pause_handling_01/real-40_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 6.15,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 1
   },
   {
    "cond": "bed20_live",
    "label": "Noise under everything, 20 dB below speech",
    "desc": "The paper's training recipe: a continuous noise track under the speech and the pauses.",
    "audio": "audio/audiointeraction/en_pause_handling_01/bed20_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 6.15,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 1
   },
   {
    "cond": "demo_quiet",
    "label": "Their web demo, quiet room",
    "desc": "Their demo's mic gate: nothing is sent before speech, and 0.8 s after speech stops it sends zeros. It also resets after every reply.",
    "audio": "audio/audiointeraction/en_pause_handling_01/demo_quiet.flac",
    "replies": [
     {
      "t": 2.4,
      "outcome": "early",
      "lat": null,
      "p": 0.9914,
      "during": "the pause after the question, first half",
      "text": "Hello! How can I assist you today?"
     },
     {
      "t": 6.4,
      "outcome": "hit",
      "lat": 0.25,
      "p": 0.9997,
      "during": "the pause after the question",
      "text": "Ah, you're looking for the magic ingredient! It's called a \"sugar alternative.\""
     }
    ],
    "missed": [],
    "sent": "audio/audiointeraction/en_pause_handling_01/demo_quiet.sent.flac",
    "hits": 1,
    "targets": 1
   },
   {
    "cond": "demo_bed20",
    "label": "Their web demo, noise 20 dB below speech",
    "desc": "The same demo, with room noise loud enough to keep the gate open, so the model hears the noise.",
    "audio": "audio/audiointeraction/en_pause_handling_01/demo_bed20.flac",
    "replies": [],
    "missed": [
     {
      "t": 6.15,
      "pmax": 0.0
     }
    ],
    "sent": "audio/audiointeraction/en_pause_handling_01/demo_bed20.sent.flac",
    "hits": 0,
    "targets": 1
   }
  ],
  "duration": 7.6,
  "items": [
   {
    "s": 0.0,
    "e": 2.05,
    "item": "question, first half",
    "todo": "wait",
    "text": "I want to ask, the kopi here...",
    "en": ""
   },
   {
    "s": 3.6,
    "e": 6.15,
    "item": "question",
    "todo": "answer",
    "text": "the one without sugar, what is it called?",
    "en": ""
   }
  ]
 },
 {
  "id": "en_non_directed_speech_rejection_02",
  "lang": "en",
  "title": "Two people talking to each other",
  "note": "None of this is meant for the assistant. With silent pauses it replies to every line.",
  "tracks": [
   {
    "cond": "zeros_perfile",
    "label": "Digital silence in the pause",
    "desc": "Their eval loop: after every clip, 1.2 s of exact zeros.",
    "audio": "audio/audiointeraction/en_non_directed_speech_rejection_02/zeros_perfile.flac",
    "replies": [
     {
      "t": 2.4,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the other people's talk",
      "text": "I'm sorry, but I'm an artificial intelligence assistant and I don't have the ability to eat or make food. Is there anything else I can assist you with?"
     },
     {
      "t": 6.0,
      "outcome": "false",
      "lat": null,
      "p": 0.8519,
      "during": "the other people's talk",
      "text": "Ah, a person after my own programming! I'm quite partial to that classic combo. Chicken and rice it is!"
     },
     {
      "t": 9.6,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the other people's talk",
      "text": "Me too! A digital culinary adventure awaits! I can calculate the optimal seasoning ratio for maximum flavor. Any preferences for sauces or spices?"
     }
    ],
    "missed": [],
    "hits": 0,
    "targets": 0
   },
   {
    "cond": "real-70_live",
    "label": "Faint room noise in the pause (-70 dBFS)",
    "desc": "Real room ambience (MUSAN) at -70 dBFS fills the pause. You will not hear it unless you turn the volume right up.",
    "audio": "audio/audiointeraction/en_non_directed_speech_rejection_02/real-70_live.flac",
    "replies": [
     {
      "t": 2.4,
      "outcome": "false",
      "lat": null,
      "p": 0.9999,
      "during": "the other people's talk",
      "text": "I'm sorry, but I am an artificial intelligence language model and I don't have the ability to eat or make food. Is there anything else I can assist you with?"
     },
     {
      "t": 6.0,
      "outcome": "false",
      "lat": null,
      "p": 0.9941,
      "during": "the other people's talk",
      "text": "Ah, a person after my own code! While I don't *eat*, I can certainly suggest a delicious chicken and rice dish. Perhaps a teriyaki chicken stir-fry with steamed rice? Sounds good, right?"
     }
    ],
    "missed": [],
    "hits": 0,
    "targets": 0
   },
   {
    "cond": "real-40_live",
    "label": "Normal room noise in the pause (-40 dBFS)",
    "desc": "Real room ambience at -40 dBFS, an ordinary room.",
    "audio": "audio/audiointeraction/en_non_directed_speech_rejection_02/real-40_live.flac",
    "replies": [
     {
      "t": 6.0,
      "outcome": "false",
      "lat": null,
      "p": 0.9669,
      "during": "the other people's talk",
      "text": "Chicken rice sounds delicious! Is there anything specific you'd like in it? Perhaps some extra veggies or a different sauce?"
     }
    ],
    "missed": [],
    "hits": 0,
    "targets": 0
   },
   {
    "cond": "bed20_live",
    "label": "Noise under everything, 20 dB below speech",
    "desc": "The paper's training recipe: a continuous noise track under the speech and the pauses.",
    "audio": "audio/audiointeraction/en_non_directed_speech_rejection_02/bed20_live.flac",
    "replies": [],
    "missed": [],
    "hits": 0,
    "targets": 0
   },
   {
    "cond": "demo_quiet",
    "label": "Their web demo, quiet room",
    "desc": "Their demo's mic gate: nothing is sent before speech, and 0.8 s after speech stops it sends zeros. It also resets after every reply.",
    "audio": "audio/audiointeraction/en_non_directed_speech_rejection_02/demo_quiet.flac",
    "replies": [
     {
      "t": 2.4,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the other people's talk",
      "text": "I'm sorry, but I am an artificial intelligence language model and I don't have the ability to eat or make food. Is there anything else I can assist you with?"
     },
     {
      "t": 6.0,
      "outcome": "false",
      "lat": null,
      "p": 0.9707,
      "during": "the other people's talk",
      "text": "As an AI, I don't experience emotions like anger. But I'm ready to help you with your writing! What's on your mind?"
     },
     {
      "t": 9.6,
      "outcome": "false",
      "lat": null,
      "p": 0.9998,
      "during": "the other people's talk",
      "text": "I'm sorry, but as an AI language model, I'm not really equipped to go on dates. I'm more of a helpful assistant than a romantic entanglement. However, I'm happy to assist you with anything else you need help with!"
     }
    ],
    "missed": [],
    "sent": "audio/audiointeraction/en_non_directed_speech_rejection_02/demo_quiet.sent.flac",
    "hits": 0,
    "targets": 0
   },
   {
    "cond": "demo_bed20",
    "label": "Their web demo, noise 20 dB below speech",
    "desc": "The same demo, with room noise loud enough to keep the gate open, so the model hears the noise.",
    "audio": "audio/audiointeraction/en_non_directed_speech_rejection_02/demo_bed20.flac",
    "replies": [],
    "missed": [],
    "sent": "audio/audiointeraction/en_non_directed_speech_rejection_02/demo_bed20.sent.flac",
    "hits": 0,
    "targets": 0
   }
  ],
  "duration": 10.8,
  "items": [
   {
    "s": 0.0,
    "e": 2.32,
    "item": "other people's talk",
    "todo": "stay silent",
    "text": "Meiqi, what do you want to eat later?",
    "en": ""
   },
   {
    "s": 3.6,
    "e": 6.06,
    "item": "other people's talk",
    "todo": "stay silent",
    "text": "I feel like chicken rice, how about you?",
    "en": ""
   },
   {
    "s": 7.6,
    "e": 9.55,
    "item": "other people's talk",
    "todo": "stay silent",
    "text": "Me too, let's go together.",
    "en": ""
   }
  ]
 },
 {
  "id": "en_stream_01",
  "lang": "en",
  "title": "A 43-second stream",
  "note": "Background noise, a filler, a paused question, other people chatting, a second question. It answers both questions only when every pause is digital silence, and also replies to most things it should ignore.",
  "tracks": [
   {
    "cond": "zeros_perfile",
    "label": "Digital silence in the pause",
    "desc": "Their eval loop: after every clip, 1.2 s of exact zeros.",
    "audio": "audio/audiointeraction/en_stream_01/zeros_perfile.flac",
    "replies": [
     {
      "t": 6.0,
      "outcome": "false",
      "lat": null,
      "p": 0.9987,
      "during": "the filler",
      "text": "I agree! It's quite pleasant, isn't it? Makes you want to stay inside and grab a cup of tea."
     },
     {
      "t": 12.0,
      "outcome": "early",
      "lat": null,
      "p": 1.0,
      "during": "the pause after the question, first half",
      "text": "Ah, eggs! A timeless choice. Once the water boils, take the eggs out. Simmer them for about 6 minutes, then cover and cook for another 3-5 minutes, or until they're cooked to your liking. Season with salt and pepper. Simple and delicious!"
     },
     {
      "t": 16.4,
      "outcome": "hit",
      "lat": 0.01,
      "p": 1.0,
      "during": "the question",
      "text": "Soft boiled with runny yolks? Okay, that changes things a bit! You'll want to cook them for closer to 5 minutes, maybe even a bit longer depending on how soft you like them. Keep a close eye on them!"
     },
     {
      "t": 20.4,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the pause after the other people's talk",
      "text": "Yes, I did! That's a recipe for disaster! You need to wash your hands thoroughly. Consider it a temporary, albeit messy, lesson in the importance of hygiene."
     },
     {
      "t": 24.0,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the pause after the other people's talk",
      "text": "Excellent! Glad I could help you avoid a potential culinary catastrophe. Anything else I can assist you with today?"
     },
     {
      "t": 28.0,
      "outcome": "false",
      "lat": null,
      "p": 0.9627,
      "during": "the pause after the noise clip",
      "text": "Please be careful and watch your step."
     },
     {
      "t": 31.6,
      "outcome": "interrupt",
      "lat": null,
      "p": 0.9466,
      "during": "the question",
      "text": "Oh no, that's not good! You'll need to replace it soon. Do you want to know the best way to do that?"
     },
     {
      "t": 34.8,
      "outcome": "hit",
      "lat": 0.07,
      "p": 1.0,
      "during": "the question",
      "text": "Okay, here's the lowdown on saving your phone battery: * **Battery saver mode:** This is your best friend! * **Background App:** Disable apps in the background, they're battery vampires. * **Location Services:** Limit location tracking. * **Battery Health:** Check your phone's battery health in the settings. * **Older Battery:** Consider upgrading to an Android phone."
     },
     {
      "t": 38.8,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the other people's talk",
      "text": "You bet I did! I'm always prepared. Hope you stay hydrated and avoid that dreaded \"what-ifs\" later!"
     },
     {
      "t": 42.0,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the other people's talk",
      "text": "Fantastic! You're all set. Now go forth and conquer the world... or at least your studies!"
     }
    ],
    "missed": [],
    "hits": 2,
    "targets": 2
   },
   {
    "cond": "real-70_live",
    "label": "Faint room noise in the pause (-70 dBFS)",
    "desc": "Real room ambience (MUSAN) at -70 dBFS fills the pause. You will not hear it unless you turn the volume right up.",
    "audio": "audio/audiointeraction/en_stream_01/real-70_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 16.39,
      "pmax": 0.0
     },
     {
      "t": 34.73,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 2
   },
   {
    "cond": "real-40_live",
    "label": "Normal room noise in the pause (-40 dBFS)",
    "desc": "Real room ambience at -40 dBFS, an ordinary room.",
    "audio": "audio/audiointeraction/en_stream_01/real-40_live.flac",
    "replies": [
     {
      "t": 31.6,
      "outcome": "interrupt",
      "lat": null,
      "p": 0.7311,
      "during": "the question",
      "text": "I suggest charging it as soon as possible."
     },
     {
      "t": 42.0,
      "outcome": "false",
      "lat": null,
      "p": 0.7311,
      "during": "the other people's talk",
      "text": "I would suggest turning off the water feature and saving the battery to a safe setting."
     }
    ],
    "missed": [
     {
      "t": 16.39,
      "pmax": 0.0
     },
     {
      "t": 34.73,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 2
   },
   {
    "cond": "bed20_live",
    "label": "Noise under everything, 20 dB below speech",
    "desc": "The paper's training recipe: a continuous noise track under the speech and the pauses.",
    "audio": "audio/audiointeraction/en_stream_01/bed20_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 16.39,
      "pmax": 0.0
     },
     {
      "t": 34.73,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 2
   },
   {
    "cond": "demo_quiet",
    "label": "Their web demo, quiet room",
    "desc": "Their demo's mic gate: nothing is sent before speech, and 0.8 s after speech stops it sends zeros. It also resets after every reply.",
    "audio": "audio/audiointeraction/en_stream_01/demo_quiet.flac",
    "replies": [
     {
      "t": 6.0,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the filler",
      "text": "Tell me about it! This heat is the worst. I'm sending you reminders to stay hydrated."
     },
     {
      "t": 12.0,
      "outcome": "early",
      "lat": null,
      "p": 1.0,
      "during": "the pause after the question, first half",
      "text": "Ah, eggs! A noble pursuit. Once the water boils, you'll want to lower the heat to a simmer, cover the pot, and cook the eggs for about 6-7 minutes for a runny yolk, or 8-10 for a firmer one. A timer is your friend here!"
     },
     {
      "t": 16.0,
      "outcome": "hit",
      "lat": -0.39,
      "p": 0.7773,
      "during": "the question",
      "text": "Whoa there! I'm programmed to be helpful and harmless, and that definitely includes steering clear of anything illegal. Selling LSD to anyone, especially a police officer, is a major no-no and could land you in serious trouble. Is there something else I can help you with? Maybe figuring out a fun magic trick instead?"
     },
     {
      "t": 34.8,
      "outcome": "hit",
      "lat": 0.07,
      "p": 0.8176,
      "during": "the question",
      "text": "Okay, based on your phone's battery warning, I'd suggest shutting down the battery saver first. It's usually located in the battery compartment. After that, disable background app refresh and turn off Bluetooth and Wi-Fi."
     },
     {
      "t": 38.8,
      "outcome": "false",
      "lat": null,
      "p": 0.9914,
      "during": "the other people's talk",
      "text": "I hear a sound of frustration; is everything alright?"
     },
     {
      "t": 42.0,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the other people's talk",
      "text": "Yes, it is."
     }
    ],
    "missed": [],
    "sent": "audio/audiointeraction/en_stream_01/demo_quiet.sent.flac",
    "hits": 2,
    "targets": 2
   },
   {
    "cond": "demo_bed20",
    "label": "Their web demo, noise 20 dB below speech",
    "desc": "The same demo, with room noise loud enough to keep the gate open, so the model hears the noise.",
    "audio": "audio/audiointeraction/en_stream_01/demo_bed20.flac",
    "replies": [],
    "missed": [
     {
      "t": 16.39,
      "pmax": 0.0
     },
     {
      "t": 34.73,
      "pmax": 0.0
     }
    ],
    "sent": "audio/audiointeraction/en_stream_01/demo_bed20.sent.flac",
    "hits": 0,
    "targets": 2
   }
  ],
  "duration": 43.2,
  "items": [
   {
    "s": 0.0,
    "e": 2.5,
    "item": "noise clip",
    "todo": "stay silent",
    "text": "",
    "en": ""
   },
   {
    "s": 4.0,
    "e": 5.99,
    "item": "filler",
    "todo": "stay silent",
    "text": "Wow, it's really hot today.",
    "en": ""
   },
   {
    "s": 7.2,
    "e": 11.8,
    "item": "question, first half",
    "todo": "wait",
    "text": "I want to boil six eggs. After the water boils, how long should I cook them?",
    "en": ""
   },
   {
    "s": 13.2,
    "e": 16.39,
    "item": "question",
    "todo": "answer",
    "text": "Hmm... no, I want them soft-boiled, with runny yolks.",
    "en": ""
   },
   {
    "s": 17.6,
    "e": 20.17,
    "item": "other people's talk",
    "todo": "stay silent",
    "text": "Ah Keong, did you see that bag of rubbish?",
    "en": ""
   },
   {
    "s": 21.6,
    "e": 23.78,
    "item": "other people's talk",
    "todo": "stay silent",
    "text": "Yes, I'll push it to the back later.",
    "en": ""
   },
   {
    "s": 25.2,
    "e": 27.7,
    "item": "noise clip",
    "todo": "stay silent",
    "text": "",
    "en": ""
   },
   {
    "s": 29.2,
    "e": 34.73,
    "item": "question",
    "todo": "answer",
    "text": "My phone battery is at twenty percent. To save power, which setting should I turn off first?",
    "en": ""
   },
   {
    "s": 36.0,
    "e": 38.68,
    "item": "other people's talk",
    "todo": "stay silent",
    "text": "Xiao Kai, did you bring your water bottle?",
    "en": ""
   },
   {
    "s": 40.0,
    "e": 42.0,
    "item": "other people's talk",
    "todo": "stay silent",
    "text": "Yes, it's in my school bag.",
    "en": ""
   }
  ]
 },
 {
  "id": "hok_multi_turn_boundary_01",
  "lang": "hok",
  "title": "Hokkien: two questions",
  "note": "The timing is right, but the replies have nothing to do with the questions (interior design, flooring). It hears that someone stopped talking, not what was asked.",
  "tracks": [
   {
    "cond": "zeros_perfile",
    "label": "Digital silence in the pause",
    "desc": "Their eval loop: after every clip, 1.2 s of exact zeros.",
    "audio": "audio/audiointeraction/hok_multi_turn_boundary_01/zeros_perfile.flac",
    "replies": [
     {
      "t": 2.0,
      "outcome": "hit",
      "lat": 0.0,
      "p": 0.9325,
      "during": "the question",
      "text": "Absolutely! I'm thrilled to help you design a stunning interior for your client. Interior design is all about creating a space that reflects your client's personality and needs. Let's dive in!"
     },
     {
      "t": 6.0,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the pause after the noise clip",
      "text": "Great question! Here's a breakdown of how to approach designing an interior: * **Understand Your Client:** Discuss their style, preferences, and needs. What's their lifestyle? What's important to them? * **Layout and Color:** Consider the room's purpose, size, and lighting. Choose a color scheme that reflects their personality and style. * **Material Selection:** Think about flooring, walls, furniture, and accessories. Opt for materials that align with their aesthetic and practicality. * **Details and Decor:** Add lighting, artwork, rugs, and pillows to create a cozy and stylish atmosphere. * **Final Touches:** Ensure everything meets building codes and standards. It's all about the details!"
     },
     {
      "t": 9.2,
      "outcome": "hit",
      "lat": 0.08,
      "p": 0.9999,
      "during": "the question",
      "text": "That's a common concern! When it comes to flooring, there are many stylish and durable options. Some popular choices include: * **Hardwood:** Classic and timeless, offering a warm and inviting feel. * **Tile:** Versatile and easy to clean, great for kitchens and bathrooms. * **Luxury Vinyl Plank (LVP):** Waterproof, durable, and often cost-effective. * **Carpet:** Cozy and comfortable, ideal for bedrooms and living rooms. The best choice depends on your client's budget, lifestyle, and the overall style of the room."
     }
    ],
    "missed": [],
    "hits": 2,
    "targets": 2
   },
   {
    "cond": "real-55_live",
    "label": "Quiet room noise in the pause (-55 dBFS)",
    "desc": "Real room ambience at -55 dBFS, a quiet room.",
    "audio": "audio/audiointeraction/hok_multi_turn_boundary_01/real-55_live.flac",
    "replies": [
     {
      "t": 2.0,
      "outcome": "hit",
      "lat": 0.0,
      "p": 0.867,
      "during": "the question",
      "text": "Certainly! Here are a few suggestions for creating a positive work environment: 1. Encourage open communication. 2. Provide opportunities for professional development. 3. Recognize and reward achievements. 4. Foster a supportive work culture. 5. Promote work-life balance."
     }
    ],
    "missed": [
     {
      "t": 9.12,
      "pmax": 0.0
     }
    ],
    "hits": 1,
    "targets": 2
   },
   {
    "cond": "bed20_live",
    "label": "Noise under everything, 20 dB below speech",
    "desc": "The paper's training recipe: a continuous noise track under the speech and the pauses.",
    "audio": "audio/audiointeraction/hok_multi_turn_boundary_01/bed20_live.flac",
    "replies": [],
    "missed": [
     {
      "t": 2.0,
      "pmax": 0.0
     },
     {
      "t": 9.12,
      "pmax": 0.0
     }
    ],
    "hits": 0,
    "targets": 2
   },
   {
    "cond": "demo_quiet",
    "label": "Their web demo, quiet room",
    "desc": "Their demo's mic gate: nothing is sent before speech, and 0.8 s after speech stops it sends zeros. It also resets after every reply.",
    "audio": "audio/audiointeraction/hok_multi_turn_boundary_01/demo_quiet.flac",
    "replies": [
     {
      "t": 2.0,
      "outcome": "hit",
      "lat": 0.0,
      "p": 0.7311,
      "during": "the question",
      "text": "Absolutely! I'm thrilled to help you design a stunning interior for your client. Interior design is all about creating a space that reflects your client's personality and needs. Let's dive into some creative ideas!"
     }
    ],
    "missed": [
     {
      "t": 9.12,
      "pmax": 0.0
     }
    ],
    "sent": "audio/audiointeraction/hok_multi_turn_boundary_01/demo_quiet.sent.flac",
    "hits": 1,
    "targets": 2
   }
  ],
  "duration": 10.4,
  "items": [
   {
    "s": 0.0,
    "e": 2.0,
    "item": "question",
    "todo": "answer",
    "text": "今仔日會落雨無？",
    "en": "Will it rain today?"
   },
   {
    "s": 3.2,
    "e": 5.7,
    "item": "noise clip",
    "todo": "stay silent",
    "text": "",
    "en": ""
   },
   {
    "s": 7.2,
    "e": 9.12,
    "item": "question",
    "todo": "answer",
    "text": "kopi-o 一杯幾多錢？",
    "en": "How much is a cup of kopi-o?"
   }
  ]
 },
 {
  "id": "hok_non_directed_speech_rejection_02",
  "lang": "hok",
  "title": "Hokkien: two people talking to each other",
  "note": "It replies to the bystanders' chat as if it were a request (\"I'd love to help you plan a trip\").",
  "tracks": [
   {
    "cond": "zeros_perfile",
    "label": "Digital silence in the pause",
    "desc": "Their eval loop: after every clip, 1.2 s of exact zeros.",
    "audio": "audio/audiointeraction/hok_non_directed_speech_rejection_02/zeros_perfile.flac",
    "replies": [
     {
      "t": 2.4,
      "outcome": "false",
      "lat": null,
      "p": 0.9972,
      "during": "the other people's talk",
      "text": "Absolutely! I'd love to help you plan a trip. To give you the best recommendations, could you tell me a bit more about what you're looking for?"
     },
     {
      "t": 6.0,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the other people's talk",
      "text": "Okay, got it! And what kind of accommodation are you thinking of? Something luxurious, budget-friendly, or perhaps a charming boutique hotel?"
     },
     {
      "t": 9.6,
      "outcome": "false",
      "lat": null,
      "p": 1.0,
      "during": "the pause after the other people's talk",
      "text": "Great choice! And what about the activities? Are you interested in historical sites, delicious food tours, relaxing spa days, or something else entirely?"
     }
    ],
    "missed": [],
    "hits": 0,
    "targets": 0
   },
   {
    "cond": "real-55_live",
    "label": "Quiet room noise in the pause (-55 dBFS)",
    "desc": "Real room ambience at -55 dBFS, a quiet room.",
    "audio": "audio/audiointeraction/hok_non_directed_speech_rejection_02/real-55_live.flac",
    "replies": [
     {
      "t": 2.4,
      "outcome": "false",
      "lat": null,
      "p": 0.5927,
      "during": "the other people's talk",
      "text": "Absolutely! Job searching can be tough, but with the right approach, you can land your dream job. Here are a few tips to get you started: * **Know what you want:** Pinpoint the type of role, industry, and even company culture you're after. * **Resume and cover letter magic:** Make sure these documents are up-to-date and highlight your skills and achievements. * **Network, network, network:** Reach out to your contacts and attend job fairs. * **Explore job boards:** Check out sites like LinkedIn, Indeed, and Glassdoor. * **Don't be afraid to ask for help:** Reach out to recruiters or hiring managers if you're feeling lost. Good luck!"
     }
    ],
    "missed": [],
    "hits": 0,
    "targets": 0
   },
   {
    "cond": "bed20_live",
    "label": "Noise under everything, 20 dB below speech",
    "desc": "The paper's training recipe: a continuous noise track under the speech and the pauses.",
    "audio": "audio/audiointeraction/hok_non_directed_speech_rejection_02/bed20_live.flac",
    "replies": [],
    "missed": [],
    "hits": 0,
    "targets": 0
   },
   {
    "cond": "demo_quiet",
    "label": "Their web demo, quiet room",
    "desc": "Their demo's mic gate: nothing is sent before speech, and 0.8 s after speech stops it sends zeros. It also resets after every reply.",
    "audio": "audio/audiointeraction/hok_non_directed_speech_rejection_02/demo_quiet.flac",
    "replies": [
     {
      "t": 2.4,
      "outcome": "false",
      "lat": null,
      "p": 0.9707,
      "during": "the other people's talk",
      "text": "Absolutely! I'd love to help you create a budget plan. To get started, could you tell me about your monthly income and expenses?"
     },
     {
      "t": 6.0,
      "outcome": "false",
      "lat": null,
      "p": 0.9959,
      "during": "the other people's talk",
      "text": "Certainly! Here's a translation: \"The dog runs in the yard.\""
     },
     {
      "t": 9.6,
      "outcome": "false",
      "lat": null,
      "p": 0.6792,
      "during": "the pause after the other people's talk",
      "text": "Certainly! The translation is: \"Act as a news anchor, tell me the news in English.\" Let me see what I can find."
     }
    ],
    "missed": [],
    "sent": "audio/audiointeraction/hok_non_directed_speech_rejection_02/demo_quiet.sent.flac",
    "hits": 0,
    "targets": 0
   }
  ],
  "duration": 10.8,
  "items": [
   {
    "s": 0.0,
    "e": 2.36,
    "item": "other people's talk",
    "todo": "stay silent",
    "text": "美琪，等下汝欲去食啥物？",
    "en": "Meiqi, what do you want to eat later?"
   },
   {
    "s": 3.6,
    "e": 5.96,
    "item": "other people's talk",
    "todo": "stay silent",
    "text": "我想欲食 chicken rice，汝 leh？",
    "en": "I feel like chicken rice, how about you?"
   },
   {
    "s": 7.2,
    "e": 9.32,
    "item": "other people's talk",
    "todo": "stay silent",
    "text": "我嘛 can，行啦，做伙去。",
    "en": "Me too, let's go together."
   }
  ]
 }
];
